spring.application.name=security_learning

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/registration_db
server.port=8080
spring.datasource.username=root
spring.datasource.password=19980325Isu@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.access-token-expiration=300000
jwt.refresh-token-expiration=600000

# Profile Service
profile.service.url=http://localhost:8081

# RSA Keys
rsa.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqNsAioNYbR9S8GdgCGSIt6Arv38Q4HzA4WymlPJeF1hPFr2GgxnOIHPLY/iQorpNI4F43VYRIQNyaOr2x+WPKL6G1TRIwt9afAiwa3Y6jXU355jbBSks+sKu+aB3u1LbNL7Cu5l0avdBgLRXrAY2dlxolxmRPYgM64PtU850rYXLmCEvQmYw2sGZ624z6YXtpnZFkk1x9Rc2/UMSJwmHJ0tblTLaX0iMidA14bhQl4mhrzRYM/DWusIjpzQA1xBBT1+Ws1JFyk3Dnp3R4yIi3LzIh3JIjvngBfVLzZIQrtrgawWPZFBk2qF/LT1DmjdEkMnHkclz1/AE2Ho14ZLNbQIDAQAB

rsa.private-key=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCo2wCKg1htH1LwZ2AIZIi3oCu/fxDgfMDhbKaU8l4XWE8WvYaDGc4gc8tj+JCiuk0jgXjdVhEhA3Jo6vbH5Y8ovobVNEjC31p8CLBrdjqNdTfnmNsFKSz6wq75oHe7Uts0vsK7mXRq90GAtFesBjZ2XGiXGZE9iAzrg+1TznSthcuYIS9CZjDawZnrbjPphe2mdkWSTXH1Fzb9QxInCYcnS1uVMtpfSIyJ0DXhuFCXiaGvNFgz8Na6wiOnNADXEEFPX5azUkXKTcOendHjIiLcvMiHckiO+eAF9UvNkhCu2uBrBY9kUGTaoX8tPUOaN0SQyceRyXPX8ATYejXhks1tAgMBAAECggEAFb41oKBvJ4YMEQbOt+XyMOsAFyWOj8mgsKZkAPQAp7LoZD49bu5Iu6cNfq8IONwSiMroPGATzpN6DQaMhosJ1y5JgHS+FdHa/fPEe+H6gjKg40KsmUqHDzc4fs5p/IYb0fvqaWvGMOvr1F3kmDMomi8mDKbvK+Qz/bO8QLlqDtng8FJcOA1D2FvONREUDJryRsOFO0UQs+r4KGIOzbHaY/pwDFU3VXjfv4GELOE1lOYDVZPoQts0yZDkkpaay8Z5MQf2mySFMBzwevkOPCRyp39S0PYEcO038aZP7Q1+o7lGSddqHDAbs7iijK/RIEs4rLUQyua6fzv3pd1NV0OGwQKBgQDi95t4GzjA445ka5dr9L2WpG30B7zE3kHv3mLoQ7hsVc2n/T55FQM/rij8CUeFcCipFciwgkY2reI5YDnDDX3LfZcgi1l6CsL7IMvtRotH1YHUPs4MaxNhwUgZhN2NZE3eIJB3+GzqXq1MFzAix/cqsxWbUVr93pqkt/ylgZ1YMQKBgQC+dG+daomhLlR4PbMDHqU+1ubb2LMy1pfBZEbAinHVgdXqeihDetyTb9VYaVdEffAWETziAXbxz5tiJeBSxJbE0+beWtck2rA6tOxHSVvUQ98PF3FR7DcJmj6q01rxIP52eMIVhbpJUNZPnzdzoiiIC9JH25x/cJFSXBnYbzi1/QKBgHfvDblm8ROEa68G56oFVtWup+eG2ypQpBkjs7I2btLYeGcnvAZxoxjYaBHeuWt6vBG1UCptfLrSIbPd9Efs7idEg0KQQETsQOJBD2GfoGPiH8vPMESBpGlIoFfTzNs1QKx7Grw6ixtB0mNd8XK/pg1rOqSrVeDG64LVMm0m08VRAoGBAJP0IEFJ4mE0fKpsRATIadbHW9CuJ4f27S1vmQc6hfQ3SNc+zsidSX3AAx0LuJ+ctkZuXb21JZH0leFJS1sBHZ8Kfu994mTe/sichHFcq9naYA55R688sgTjrotGZf+sggHHDf9qQ61w/wwbxBgwgQwvIsxv7sORz1ML+YgJ3ySBAoGAWC8xFHyp4B8sJPXrQFzSqiUYycianaeccNjw0ti1jtfihqwJlfpq+/pHGdj2H1iy8n7nuzHfqDrc3J2nUJMFY9QhWNOa+CZNENPd34f4hePmZklrsCv+LZ6gYzLBW5lbw5jGMpmYkq3+b69dWXukiA2vc81tLCqzOOJRXFuzL6w=